"""empty message

Revision ID: 1ae9f98b49e1
Revises: bcd07fec1e2a
Create Date: 2021-06-23 13:03:41.813308

"""

# revision identifiers, used by Alembic.
revision = '1ae9f98b49e1'
down_revision = 'bcd07fec1e2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
