"""empty message

Revision ID: bcd07fec1e2a
Revises: 51f5ccfba190
Create Date: 2021-06-23 12:41:09.466454

"""

# revision identifiers, used by Alembic.
revision = 'bcd07fec1e2a'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
