"""empty message

Revision ID: ce2d820a6cee
Revises: 1ae9f98b49e1
Create Date: 2021-06-23 13:45:35.676742

"""

# revision identifiers, used by Alembic.
revision = 'ce2d820a6cee'
down_revision = '1ae9f98b49e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
